language: java

sudo: true

install:
 - wget -O - https://github.com/jphp-compiler/jphp/releases/download/jppm-0.3.8/jppm-setup-0.3.8.sh | bash
os: 
 - linux

jdk: 
 - oraclejdk10
 - oraclejdk9
 
script:
 - jppm version
 - jppm prepare-ide
 - jppm build-ide
