language: java

sudo: true

before_install:
 - wget -O - https://github.com/jphp-compiler/jphp/releases/download/jppm-0.3.8/jppm-setup-0.3.8.sh | bash
os: linux

jdk: 
 - openjdk10
 
addons:
  apt:
    packages:
      - oracle-java10-installer
 
script:
 - jppm version
 - jppm prepare-ide
 - jppm build-ide
