{
  "props": [],
  "components": {
    "zipChooser": {
      "type": "script\\FileChooserScript",
      "x": 80,
      "y": 16,
      "props": {
        "filterName": "Плагины для ND CORE",
        "filterExtensions": "*.zip",
        "filterAny": false,
        "inputNode": "",
        "actionNode": ""
      }
    },
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 16,
      "y": 16,
      "props": {
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}