{
  "props": [],
  "components": {
    "zipChooser": {
      "type": "script\\FileChooserScript",
      "x": 80,
      "y": 16,
      "props": {
        "filterName": "",
        "filterExtensions": "*.ndplugin",
        "filterAny": false,
        "inputNode": "",
        "actionNode": ""
      }
    },
    "githubClient": {
      "type": "bundle\\http\\HttpClient",
      "x": 144,
      "y": 16,
      "props": {
        "baseUrl": "https://api.github.com",
        "requestType": "URLENCODE",
        "responseType": "JSON",
        "connectTimeout": "15000",
        "readTimeout": "0",
        "followRedirects": "1",
        "proxyType": "HTTP",
        "userAgent": "Nearde IDE 2.0"
      }
    },
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 16,
      "y": 16,
      "props": {
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}